<Writer>:
    orientation: 'vertical'
    Bios:
        id: bios
    Button:
        id: writeBtn
        text: 'Write'
        size_hint: 1,None
        height: root.height/9
        on_press: root.collectData()
    Label:
        id: writeLbl
        text: 'place your card/key to write'
        size_hint: 1,None
        height: root.height/27
    Status:
        id: status
        size_hint: 1,None
        height: root.height/9